<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BotigaSync.Contracts\BotigaSync.Contracts.csproj" />
    <ProjectReference Include="..\BotigaSync.Entity\BotigaSync.Entity.csproj" />
    <ProjectReference Include="..\BotigaSync.Repository\BotigaSync.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Serilog" Version="3.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
